version: '3.7'

services:
  vault-server:
    image: hashicorp/vault-enterprise:1.10.4-ent
    hostname: vault
    container_name: vault
    network_mode: host
    environment:
      VAULT_ADDR: "http://127.0.0.1:8200"
    volumes:
      - /var/docker/vault/file:/vault/file
      - /var/docker/vault/config:/vault/config
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config.hcl
  pihole:
    container_name: pihole2
    image: pihole/pihole:latest
    network_mode: host
    environment:
      TZ: 'America/New_York'
      # WEBPASSWORD: 'set a secure password here or it will be random'
    # Volumes store your data between container upgrades
    volumes:
      - /var/docker/etc-pihole:/etc/pihole
      - /var/docker/etc-dnsmasq.d:/etc/dnsmasq.d
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN # Recommended but not required (DHCP needs NET_ADMIN)      
    restart: unless-stopped