version: '3.7'

services:
  unifi:
    image: "jacobalberty/unifi:stable-5"
    container_name: unifi
    init: true
    restart: always
    volumes:
    network_mode: host
      - /var/docker/unifi:/unifi
    environment:
      TZ: 'America/New_York'
      RUNAS_UID0: 'false'
      UNIFI_UID: 1000
      UNIFI_GID: 1000
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    network_mode: host
    environment:
      TZ: 'America/New_York'
      # WEBPASSWORD: 'set a secure password here or it will be random'
    # Volumes store your data between container upgrades
    volumes:
      - /var/docker/etc-pihole:/etc/pihole
      - /var/docker/etc-dnsmasq.d:/etc/dnsmasq.d
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN # Recommended but not required (DHCP needs NET_ADMIN)      
    restart: unless-stopped
