version: '3.7'

services:
  vault-server:
    image: hashicorp/vault-enterprise:1.10.4-ent
    hostname: vault
    container_name: vault
    network_mode: host
    environment:
      VAULT_ADDR: "http://127.0.0.1:8200"
    volumes:
      - /etc/vault.d/file:/vault/file
      - /etc/vault.d:/vault
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config.hcl